### ISSUE TITLE
System.IO.FileNotFoundException: Could not load assembly AppFinalMITInfnet

### ISSUE THREAD

**Issue by marcioggs** [InfnetMobile/AppFinal#1]
Recebi este erro ao tentar compilar no Visual Studio 2015 para Android.
Já tentei remover o pacote Xamarin.Forms (e suas dependências) e adicioná-lo novamente, mas de nada adiantou.
Se conseguir consertar aviso aqui.

_"Error		Unexpected error - Please file a bug report at http://bugzilla.xamarin.com. Reason: System.IO.FileNotFoundException: Could not load assembly 'AppFinalMITInfnet, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?	AppFinalMITInfnet.Droid"_

**Comment by jbravobr** [comment]
Verificou se tanto o Forms quanto o mono estão atualizados?

Em sáb, 5 de nov de 2016 às 11:07, marcioggs notifications@github.com
escreveu:

**Comment by marcioggs** [comment]
Atualizei para a última versão estável do Xamarin for Visual Studio (4.2.0.719) acho que mudou um pouco o output do build, mas esse erro continua lá.
O Xamarin.Forms já estava na última versão (2.3.2.127).
O Mono não é um pacote do Nuget? Não o encontrei nos pacotes instalados. Irei pesquisar como atualizá-lo.

O output completo do build é esse:

_1>------ Build started: Project: AppFinalMITInfnet, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Humanizer" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\App.cs(1,13,1,18): error CS0234: The type or namespace name 'Unity' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(5,13,5,21): error CS0234: The type or namespace name 'Services' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(8,13,8,23): error CS0234: The type or namespace name 'Navigation' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Data\Configuration\DatabaseConfig.cs(2,13,2,21): error CS0234: The type or namespace name 'Services' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\HomePageViewModel.cs(7,13,7,23): error CS0234: The type or namespace name 'Navigation' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(7,13,7,23): error CS0234: The type or namespace name 'Navigation' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientDetailPageViewModel.cs(3,13,3,23): error CS0234: The type or namespace name 'Navigation' does not exist in the namespace 'Prism' (are you missing an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\App.cs(9,24,9,40): error CS0246: The type or namespace name 'PrismApplication' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\App.cs(15,33,15,46): error CS0115: 'App.OnInitialized()': no suitable method found to override
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\App.cs(20,33,20,46): error CS0115: 'App.RegisterTypes()': no suitable method found to override
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(30,18,30,36): error CS0246: The type or namespace name 'IPageDialogService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(31,18,31,36): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(38,35,38,53): error CS0246: The type or namespace name 'IPageDialogService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\LoginPageViewModel.cs(39,37,39,55): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\HomePageViewModel.cs(16,18,16,36): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\HomePageViewModel.cs(29,34,29,52): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(14,58,14,74): error CS0246: The type or namespace name 'INavigationAware' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(83,37,83,57): error CS0246: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(87,35,87,55): error CS0246: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(18,18,18,36): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientListPageViewModel.cs(44,40,44,58): error CS0246: The type or namespace name 'INavigationService' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientDetailPageViewModel.cs(11,60,11,76): error CS0246: The type or namespace name 'INavigationAware' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientDetailPageViewModel.cs(120,37,120,57): error CS0246: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ViewModel\ClientDetailPageViewModel.cs(124,35,124,55): error CS0246: The type or namespace name 'NavigationParameters' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(16,49,16,65): warning CS0108: 'CustomLoginEntry.FontSizeProperty' hides inherited member 'Entry.FontSizeProperty'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(19,23,19,31): warning CS0108: 'CustomLoginEntry.FontSize' hides inherited member 'Entry.FontSize'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(25,49,25,73): warning CS0108: 'CustomLoginEntry.PlaceholderColorProperty' hides inherited member 'Entry.PlaceholderColorProperty'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(28,22,28,38): warning CS0108: 'CustomLoginEntry.PlaceholderColor' hides inherited member 'Entry.PlaceholderColor'. Use the new keyword if hiding was intended.
2>------ Build started: Project: AppFinalMITInfnet.Droid, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'AppFinalMITInfnet, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: File name: 'AppFinalMITInfnet.dll'
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
3>------ Skipped Deploy: Project: AppFinalMITInfnet.Droid, Configuration: Debug Any CPU ------
3>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========
All packages are already installed and there is nothing to restore._

**Comment by marcioggs** [comment]
No caso a atualização do Mono é só para Mac, certo?
Para Windows devo atualizar o .NET framework? O target atual é v4.5.

Vi que a primeira linha de erro é esta:
_C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Humanizer" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259"._

Estou vendo como atualizar para a versão 5.0 do .NET, mas não aparece nos targets, e nem na página para instalar novos targets.

**Comment by marcioggs** [comment]
Estavam faltando algumas dependências. As reinstalei e o output reduziu, mas continua com o erro inicial.

_1>------ Build started: Project: AppFinalMITInfnet, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "Humanizer" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile259".
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(16,49,16,65): warning CS0108: 'CustomLoginEntry.FontSizeProperty' hides inherited member 'Entry.FontSizeProperty'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(19,23,19,31): warning CS0108: 'CustomLoginEntry.FontSize' hides inherited member 'Entry.FontSize'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(25,49,25,73): warning CS0108: 'CustomLoginEntry.PlaceholderColorProperty' hides inherited member 'Entry.PlaceholderColorProperty'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(28,22,28,38): warning CS0108: 'CustomLoginEntry.PlaceholderColor' hides inherited member 'Entry.PlaceholderColor'. Use the new keyword if hiding was intended.
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(8,13,8,94): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(17,13,17,102): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Renderers\CustomLoginEntry.cs(26,13,26,100): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\Domain\Name.cs(12,43,12,52): error CS0103: The name 'Humanizer' does not exist in the current context
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ApiService\ApiService.cs(11,37,11,42): warning CS0169: The field 'ApiService<T>._repo' is never used
1>C:\Users\marcioggs\Source\Repos\AppFinal\AppFinalMITInfnet\ApplicationService\BaseApplicationService.cs(10,37,10,48): warning CS0649: Field 'BaseApplicationService<T>._repository' is never assigned to, and will always have its default value null
2>------ Build started: Project: AppFinalMITInfnet.Droid, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'AppFinalMITInfnet, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018: File name: 'AppFinalMITInfnet.dll'
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1054,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
3>------ Skipped Deploy: Project: AppFinalMITInfnet.Droid, Configuration: Debug Any CPU ------
3>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========_

**Comment by jbravobr** [comment]
Certo, a biblioteca Humanizer está tentando baixar uma versão não
compatível com o composto do seu PCL. Parece que o seu PCL está configurado
para NET Standard. Duas opções (tentativas), 1) trocar o humanizer para uma
outra versão (maior talvez), 2) trocar o profile do seu PCL de 249 para 111
ou 78
Em sáb, 5 de nov de 2016 às 12:28, marcioggs notifications@github.com
escreveu:

**Comment by jbravobr** [comment]
Marcio, veja que no próprio repositório do Humanizer (library usada neste exemplo) é apontado o erro na própria Library. https://github.com/Humanizr/Humanizer/issues/573

Estou baixando o repo para o meu VS e vou avaliar.

**Comment by marcioggs** [comment]
O PCL profile é determinado pela combinação dos targets selecionados?
Tentei algumas combinações, mas nada funcionou, e também não consegui descobrir quais combinações são PCL 111 e 78.

**Comment by jbravobr** [comment]
Estou fora, a noite eu vou avaliar isto e dou uma solução. A mais rápida é
remover o Humanizer, mas é usado

Em sáb, 5 de nov de 2016 às 17:11, marcioggs notifications@github.com
escreveu:

**Comment by marcioggs** [comment]
Downgrade para versão 1.0.1 do Humanizer resolve.
